### ISSUE TITLE
cli-etp installation on akamai cli for windows pip error

### ISSUE THREAD

**Issue by MicMax500** [akamai/cli-etp#3]
during installation with 'akamai installa etp' comman on a Win10 Machine, i get error Pip non found even if pip is whell installed, can you help me?

**Comment by bitonio** [comment]
Hi MicMax500

Make sure you have the latest Python 3 for Windows installed our your machine.
You can grab it here: https://www.python.org/downloads/windows/

You should be able to type `python` or `python3` command, and same with `pip` or `pip3`.
If you have a command not found, it is likely Python is either missing or not in the PATH variable. Sometimes all it takes is to close/quit the Windows Command Shell window, and re-open a new one.

Keep us posted!

**Comment by MicMax500** [comment]
At command prompt, I get this

**C:\>python --version
Python 3.10.3**

**C:\>pip --version
pip 21.2.4 from C:\Program Files\Python310\lib\site-packages\pip (python 3.10)**

while when i try to install a get this
**C:\>akamai install etp
Attempting to fetch command from https://github.com/akamai/cli-etp.git... [=         ] Total 219 (delta 110), reused 176                                                                                                                        Attempting to fetch command from https://github.com/akamai/cli-etp.git... ... [OK]
Installing... [==        ]  ERROR[0001] Pip not found in the system. Please verify your setup command=install
 ERROR[0001] pip not found. Please verify your setup: pip 21.2.4 from C:\Program Files\Python310\lib\site-packages\pip ( command=install
Installing... ... [FAIL]
pip not found. Please verify your setup: pip 21.2.4 from C:\Program Files\Python310\lib\site-packages\pip (python 3.10)
 ERROR[0001] pip not found. Please verify your setup: pip 21.2.4 from C:\Program Files\Python310\lib\site-packages\pip ( command=install
 ERROR[0001] INSTALL ERROR: Unable to install selected package command=install
Unable to install selected package**

Before there was pip 22.0.4, I downgrade the version in case the problem was about pip version 
TKS

**Comment by bitonio** [comment]
Thanks for sharing the detailed output of the error.

I'll need to reproduce your exact setup next week.
In the mean, I can suggest to try to install Python and PIP in a path outside "Program Files", like C:\Python\
If that works, I'll follow up with our Akamai CLI core team.

**Comment by MicMax500** [comment]
Thanks for your support.

I reinstalla under c:. I repo new result

****C:\>python --version
Python 3.10.4**

**C:\>pip --version
pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)****

**C:\>akamai install etp
Attempting to fetch command from https://github.com/akamai/cli-etp.git... [=         ] Compressing objects: 100% (139/13                                                                                                                        Attempting to fetch command from https://github.com/akamai/cli-etp.git... ... [OK]
Installing... [===       ]  ERROR[0001] Pip not found in the system. Please verify your setup command=install
 command=install not found. Please verify your setup: pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
Installing... ... [FAIL]
pip not found. Please verify your setup: pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
 command=install not found. Please verify your setup: pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
 ERROR[0001] INSTALL ERROR: Unable to install selected package command=install
Unable to install selected package**

**Comment by bitonio** [comment]
Thanks for trying. I am working on reproducing this. Will keep you posted.

**Comment by bitonio** [comment]
```
C:\Akamai>akamai --version
akamai version 1.4.1

C:\Akamai>python --version
Python 3.10.4

C:\Akamai>pip --version
pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
```
I got an error very similar to yours, I'll work with the akamai cli team to understand better where the issue lies.

```
C:\Akamai>akamai install etp
Attempting to fetch command from https://github.com/akamai/cli-etp.git... [=         ] Total 219 (delta 110), reused 176                                                                                                                        Attempting to fetch command from https://github.com/akamai/cli-etp.git... ... [OK]
Installing... [===       ]  ERROR[0001] Pip not found in the system. Please verify your setup command=install
 command=install not found. Please verify your setup: pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
Installing... ... [FAIL]
pip not found. Please verify your setup: pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
 command=install not found. Please verify your setup: pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
 ERROR[0002] INSTALL ERROR: Unable to install selected package command=install
Unable to install selected package
```

**Comment by bitonio** [comment]
I raised https://github.com/akamai/cli/issues/148 and will follow-up.

**Comment by MicMax500** [comment]
In my opinion you are on right way.
In some test I try to use AKAMAI LOG=debug env variable. Only few information more, but I had impression the problem was about parsing the command output.

Massimiliano

**Comment by bitonio** [comment]
Good point @MicMax500,

With debug flag:

```
C:\Akamai>akamai install cli-etp
 DEBUG[0000] INSTALL START             command=install
Attempting to fetch command from https://github.com/akamai/cli-etp.git... ... [OK]
 DEBUG[0001] Validating dependencies for python 3.6.0 module command=install
 DEBUG[0001] Python binary found: C:\Windows\py.exe command=install
 command=install=        ]  DEBUG[0001] C:\Windows\py.exe --version: Python 3.10.4
Installing... [====      ]  DEBUG[0002] C:\Windows\py.exe -m pip --version pip 22.0.4 from C:\Python\lib\site-packages\p: %!s(MISSING) command=install
 ERROR[0002] Pip not found in the system. Please verify your setup command=install
 command=install not found. Please verify your setup: pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
Installing... ... [FAIL]
pip not found. Please verify your setup: pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
 command=install not found. Please verify your setup: pip 22.0.4 from C:\Python\lib\site-packages\pip (python 3.10)
 ERROR[0003] INSTALL ERROR: Unable to install selected package command=install
Unable to install selected package
```

I'll investigate more tomorrow, and the CLI team is already looking at this.

In the meantime, feel free to grab the [Docker container version of our CLI](https://github.com/akamai/cli#install-with-docker) - this will work on a Windows box while we narrow this down.

**Comment by bitonio** [comment]
A fix has been implemented and will be released soon, I'll update this ticket when it is out.
For a workaround, beside the Akamai CLI Docker container, you might install Python 3.9 instead of 3.10 and start using cli-etp.

**Comment by bitonio** [comment]
Dependency on akamai-cli repo is fixed, closing this issue.
